// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5PYFevgDk2rIPI75pQ2F4VG7mcM35Tdc',
    appId: '1:574943856710:web:48e61c35b0c39809f2e247',
    messagingSenderId: '574943856710',
    projectId: 'ghostme-34590',
    authDomain: 'ghostme-34590.firebaseapp.com',
    storageBucket: 'ghostme-34590.firebasestorage.app',
    measurementId: 'G-4QXNJ1T0VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7V7ByCzFKoNDaOy8vyYW43YOe7qMxgn8',
    appId: '1:574943856710:android:92571066a164ae62f2e247',
    messagingSenderId: '574943856710',
    projectId: 'ghostme-34590',
    storageBucket: 'ghostme-34590.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpy8tJuSufxS6_7vIXlmPAQP4LDzhNWYE',
    appId: '1:574943856710:ios:28266d6e7ebe8c49f2e247',
    messagingSenderId: '574943856710',
    projectId: 'ghostme-34590',
    storageBucket: 'ghostme-34590.firebasestorage.app',
    iosClientId: '574943856710-s7m7f6ioa6o39f3sanoif952maimr7rr.apps.googleusercontent.com',
    iosBundleId: 'com.brycewayne.ghostMeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpy8tJuSufxS6_7vIXlmPAQP4LDzhNWYE',
    appId: '1:574943856710:ios:28266d6e7ebe8c49f2e247',
    messagingSenderId: '574943856710',
    projectId: 'ghostme-34590',
    storageBucket: 'ghostme-34590.firebasestorage.app',
    iosClientId: '574943856710-s7m7f6ioa6o39f3sanoif952maimr7rr.apps.googleusercontent.com',
    iosBundleId: 'com.brycewayne.ghostMeMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL5jUYd-qvFL3bKP75KUJDyhOWiXMxtm8',
    appId: '1:574943856710:web:2b4aae1bab85f711f2e247',
    messagingSenderId: '574943856710',
    projectId: 'ghostme-34590',
    authDomain: 'ghostme-34590.firebaseapp.com',
    storageBucket: 'ghostme-34590.firebasestorage.app',
    measurementId: 'G-4PTPCF5MMZ',
  );
}
